export type SiteKey = 'shopifyemailapps.com' | 'shopifysmsapps.com' | 'shopifymarketingapps.com' | 'shopifyemailmarketingapps.com' | 'shopifysmsmarketingapps.com' | 'shopifyemailmarketingtools.com' | 'shopifyemailtools.com' | 'shopifyabandonedcartapps.com';

export type SiteProfile = { domain: SiteKey; name: string; shortName: string; primaryKeyword: string; keywordPlural: string; channel: string; angle: string; heroPromise: string; bestOverallReason: string; accent: string; };
export const DOMAINS: SiteKey[] = ['shopifyemailapps.com','shopifysmsapps.com','shopifymarketingapps.com','shopifyemailmarketingapps.com','shopifysmsmarketingapps.com','shopifyemailmarketingtools.com','shopifyemailtools.com','shopifyabandonedcartapps.com'];
export const SITES: Record<SiteKey, SiteProfile> = {
 'shopifyemailapps.com': {domain:'shopifyemailapps.com',name:'Shopify Email Apps',shortName:'Email Apps',primaryKeyword:'Shopify email apps',keywordPlural:'Shopify email apps',channel:'email',angle:'email apps that turn Shopify customer, order, and product signals into lifecycle campaigns without a bloated ecommerce suite',heroPromise:'Compare the best Shopify email apps for welcome flows, product education, winbacks, segmentation, and revenue attribution.',bestOverallReason:'It balances Shopify-native ecommerce signals with flexible lifecycle automation instead of stopping at newsletter blasts.',accent:'emerald'},
 'shopifysmsapps.com': {domain:'shopifysmsapps.com',name:'Shopify SMS Apps',shortName:'SMS Apps',primaryKeyword:'Shopify SMS apps',keywordPlural:'Shopify SMS apps',channel:'sms',angle:'SMS apps that protect margins, consent, and deliverability while recovering time-sensitive Shopify revenue',heroPromise:'Compare Shopify SMS apps for opt-in capture, abandoned checkout texts, replenishment reminders, post-purchase updates, and TCPA-aware automation.',bestOverallReason:'The best SMS stack uses Shopify events carefully, throttles sends, respects quiet hours, and reserves texts for moments that need urgency.',accent:'lime'},
 'shopifymarketingapps.com': {domain:'shopifymarketingapps.com',name:'Shopify Marketing Apps',shortName:'Marketing Apps',primaryKeyword:'Shopify marketing apps',keywordPlural:'Shopify marketing apps',channel:'marketing',angle:'marketing apps that help Shopify stores coordinate email, SMS, referrals, reviews, popups, loyalty, and analytics from one practical growth stack',heroPromise:'Find Shopify marketing apps for retention, acquisition, conversion, customer data, product launches, and repeat purchase growth.',bestOverallReason:'A strong Shopify marketing stack connects owned channels, storefront behavior, and revenue reporting without creating tool sprawl.',accent:'teal'},
 'shopifyemailmarketingapps.com': {domain:'shopifyemailmarketingapps.com',name:'Shopify Email Marketing Apps',shortName:'Email Marketing Apps',primaryKeyword:'Shopify email marketing apps',keywordPlural:'Shopify email marketing apps',channel:'email',angle:'email marketing apps purpose-built for Shopify revenue, not generic newsletter software bolted onto a store',heroPromise:'Compare Shopify email marketing apps for flows, segmentation, product feeds, coupon logic, abandoned carts, and revenue reporting.',bestOverallReason:'The winner should understand Shopify orders, products, discounts, customers, and repeat purchase timing out of the box.',accent:'emerald'},
 'shopifysmsmarketingapps.com': {domain:'shopifysmsmarketingapps.com',name:'Shopify SMS Marketing Apps',shortName:'SMS Marketing Apps',primaryKeyword:'Shopify SMS marketing apps',keywordPlural:'Shopify SMS marketing apps',channel:'sms',angle:'SMS marketing apps that use restraint: fewer, better-timed texts tied directly to Shopify revenue moments',heroPromise:'Compare Shopify SMS marketing apps for compliant list growth, cart recovery, flash-sale alerts, replenishment texts, and two-way replies.',bestOverallReason:'The best app treats SMS as a high-intent channel, not a noisy discount cannon.',accent:'lime'},
 'shopifyemailmarketingtools.com': {domain:'shopifyemailmarketingtools.com',name:'Shopify Email Marketing Tools',shortName:'Email Marketing Tools',primaryKeyword:'Shopify email marketing tools',keywordPlural:'Shopify email marketing tools',channel:'email',angle:'email marketing tools for Shopify teams that want practical automation, clean segmentation, and measurable revenue lift',heroPromise:'Evaluate Shopify email marketing tools for lifecycle automation, template control, deliverability, analytics, and store data quality.',bestOverallReason:'Good tools turn Shopify behavior into timely messages and make it obvious which campaigns create incremental revenue.',accent:'green'},
 'shopifyemailtools.com': {domain:'shopifyemailtools.com',name:'Shopify Email Tools',shortName:'Email Tools',primaryKeyword:'Shopify email tools',keywordPlural:'Shopify email tools',channel:'email',angle:'email tools that cover both promotional campaigns and operational lifecycle messages for Shopify stores',heroPromise:'Compare Shopify email tools for newsletters, automations, transactional-style updates, segmentation, and customer retention.',bestOverallReason:'The right email tool makes store data usable and keeps teams from stitching together one-off newsletter and automation systems.',accent:'emerald'},
 'shopifyabandonedcartapps.com': {domain:'shopifyabandonedcartapps.com',name:'Shopify Abandoned Cart Apps',shortName:'Abandoned Cart Apps',primaryKeyword:'Shopify abandoned cart apps',keywordPlural:'Shopify abandoned cart apps',channel:'cart recovery',angle:'abandoned cart apps that recover Shopify revenue through well-timed email, SMS, product reminders, and checkout-aware logic',heroPromise:'Compare Shopify abandoned cart apps for cart recovery flows, checkout tracking, coupon testing, multi-channel reminders, and margin-safe incentives.',bestOverallReason:'A strong cart recovery app responds to cart value, product type, inventory, customer history, and consent instead of blasting everyone the same coupon.',accent:'amber'}
};

export type App = { slug:string; name:string; category:string; bestFor:string; pricing:string; strengths:string[]; limits:string[]; shopifyFit:string; channels:string[]; };
export const APPS: App[] = [
 ['klaviyo','Klaviyo','Email and SMS automation','stores that want deep ecommerce segmentation and proven Shopify-native flows','Free tier; paid plans scale by profiles and SMS volume',['deep Shopify event and catalog integrations','excellent segmentation and revenue reporting','large template and agency ecosystem'],['can get expensive as profiles grow','advanced reporting takes setup discipline'],'Klaviyo is the default benchmark for Shopify retention because it understands products, orders, checkout events, predictive metrics, and customer profiles in detail.',['email','sms','marketing','cart recovery']],
 ['omnisend','Omnisend','Email, SMS, and push','small to mid-sized Shopify stores that want multichannel automation without enterprise complexity','Free tier; Standard and Pro plans scale by contacts',['fast Shopify setup','email + SMS + push in one journey builder','strong prebuilt ecommerce automations'],['less flexible than Klaviyo for complex data models','SMS costs need monitoring'],'Omnisend is practical when a Shopify team wants cart recovery, welcome, post-purchase, and reactivation flows live quickly.',['email','sms','marketing','cart recovery']],
 ['postscript','Postscript','SMS marketing','Shopify brands that treat SMS as a revenue channel with compliance guardrails','Usage-based and plan-based pricing by message volume',['Shopify-focused SMS automation','good compliance tooling','two-way conversations and campaign controls'],['SMS-first, not a full email platform','cost discipline matters at scale'],'Postscript is best when checkout recovery, drops, replenishment, and VIP campaigns need an SMS-native workflow.',['sms','marketing','cart recovery']],
 ['attentive','Attentive','SMS and email marketing','larger DTC Shopify brands with high SMS volume and managed growth needs','Custom pricing',['excellent SMS acquisition flows','strong enterprise support','broad ecommerce integrations'],['custom pricing is not ideal for tiny stores','can be more platform than an early shop needs'],'Attentive fits Shopify brands that already have traffic, offer cadence, and list economics to justify a premium SMS program.',['sms','email','marketing','cart recovery']],
 ['yotpo-email-sms','Yotpo Email & SMS','Retention marketing suite','stores that already use or want reviews, loyalty, email, and SMS in one ecosystem','Free and paid plans; modules vary by product',['email, SMS, reviews, and loyalty ecosystem','solid Shopify integration','useful for retention consolidation'],['suite breadth can add complexity','best value when using multiple Yotpo modules'],'Yotpo is useful when retention work spans campaigns, reviews, loyalty points, UGC, and SMS rather than email alone.',['email','sms','marketing','cart recovery']],
 ['privy','Privy','Popups, email, and SMS','smaller Shopify stores that need list capture and basic campaigns fast','Free and paid plans by contacts/pageviews',['excellent popup and capture tools','simple email/SMS campaigns','beginner-friendly Shopify onboarding'],['not as deep for complex lifecycle automation','analytics are simpler than specialist tools'],'Privy works when the immediate problem is capturing more visitors and sending simple welcome, cart, and promotion messages.',['email','sms','marketing','cart recovery']],
 ['shopify-email','Shopify Email','Native email campaigns','shops that want a low-friction native email sender inside Shopify Admin','Included monthly emails, then usage-based Shopify pricing',['built directly into Shopify','uses store products and branding easily','low learning curve'],['limited automation depth','not a replacement for advanced retention platforms'],'Shopify Email is the easiest starting point for basic newsletters, product drops, and sale announcements from inside the admin.',['email','marketing']],
 ['mailchimp','Mailchimp','General email marketing','teams that already know Mailchimp and need Shopify-connected campaigns','Free and paid plans by contacts and features',['familiar campaign editor','broad marketing features','large integration ecosystem'],['Shopify depth trails ecommerce-native platforms','automation can feel generic'],'Mailchimp is acceptable for simple Shopify lists and campaigns, but stores focused on lifecycle revenue often outgrow it.',['email','marketing']],
 ['drip','Drip','Ecommerce automation','shops that want visual workflows and customer behavior segmentation','Paid plans by people in account',['strong ecommerce automation builder','good segmentation','clear revenue focus'],['smaller ecosystem than Klaviyo','interface can feel workflow-heavy for simple campaigns'],'Drip is a good fit for teams that like hands-on automation design and want behavior-based Shopify journeys.',['email','sms','marketing','cart recovery']],
 ['activecampaign','ActiveCampaign','Marketing automation and CRM','Shopify stores combining ecommerce marketing with sales follow-up or B2B workflows','Paid plans by contacts and product tier',['powerful automation logic','CRM features','broad integrations'],['less Shopify-native than ecommerce specialists','setup can become overbuilt'],'ActiveCampaign makes sense when Shopify customer journeys overlap with CRM pipelines, high-ticket sales, or consultative purchases.',['email','marketing']],
 ['brevo','Brevo','Email, SMS, and transactional messaging','budget-conscious stores that need practical campaigns and messages','Free tier; paid by email volume/features',['affordable email volume','SMS and transactional options','straightforward campaign tools'],['Shopify-specific templates and analytics are lighter','advanced ecommerce segmentation is limited'],'Brevo is a cost-aware option for Shopify stores that want dependable campaigns without premium ecommerce-platform prices.',['email','sms','marketing']],
 ['sendlane','Sendlane','Email and SMS for ecommerce','DTC brands that want retention automation with migration support','Paid plans and custom packages',['ecommerce-first automation','email + SMS coordination','strong migration/support positioning'],['less self-serve transparency than cheaper tools','best for brands ready to invest in retention'],'Sendlane fits stores that have enough order volume to justify a more guided retention platform.',['email','sms','marketing','cart recovery']],
 ['aftership-email','AfterShip Email','Email and SMS marketing','merchants already using AfterShip for post-purchase and tracking workflows','Free and paid tiers vary by product',['ties into post-purchase experience','useful shipping and tracking ecosystem','practical Shopify integrations'],['less famous as a pure email leader','best when paired with AfterShip products'],'AfterShip Email is interesting when retention messages depend on delivery, tracking, returns, and post-purchase timing.',['email','sms','marketing']],
 ['recart','Recart','SMS and messenger recovery','stores focused on cart recovery and conversational mobile channels','Paid plans/custom depending on usage',['cart recovery specialization','mobile-first reminders','good for promo-driven DTC'],['not a complete email marketing suite','channel mix may be narrower than full platforms'],'Recart is worth considering when abandoned cart recovery is the main problem and mobile reminders outperform email alone.',['sms','marketing','cart recovery']],
 ['justuno','Justuno','Conversion and list capture','stores that need advanced popups, quizzes, and on-site capture feeding email/SMS tools','Paid plans by traffic/features',['powerful onsite targeting','good quiz and popup controls','feeds lists into retention tools'],['not primarily an email sender','requires pairing with campaign tools'],'Justuno strengthens the top of the retention funnel by capturing better subscriber intent before campaigns begin.',['marketing']],
 ['rejoiner','Rejoiner','Managed email and SMS lifecycle','brands that want strategic help, not just software','Custom pricing',['lifecycle strategy support','email and SMS program help','strong for abandoned cart and retention'],['not a cheap self-serve app','fit depends on service needs'],'Rejoiner fits Shopify brands that want experts to help design, write, and optimize lifecycle campaigns.',['email','sms','marketing','cart recovery']],
 ['marsello','Marsello','Email, SMS, and loyalty','retailers combining Shopify ecommerce with loyalty and POS-driven repeat purchase','Paid plans by contacts/features',['loyalty plus campaigns','useful for omnichannel retailers','customer segmentation included'],['less specialized for pure email depth','best if loyalty is central'],'Marsello is practical for shops where loyalty, POS behavior, and repeat purchase automations are connected.',['email','sms','marketing']],
 ['firepush','Firepush','Email, SMS, and web push','stores that want push notifications alongside email and SMS recovery','Free and paid plans by impressions/messages',['multi-channel recovery','web push support','simple Shopify automations'],['not as polished as top-tier suites','push can become noisy if overused'],'Firepush is useful when web push is part of the cart recovery and promotion strategy.',['email','sms','marketing','cart recovery']],
 ['smsbump','SMSBump','SMS marketing','Shopify merchants already in the Yotpo SMS ecosystem','Usage-based SMS and plan options',['Shopify SMS automations','list growth tools','Yotpo ecosystem connection'],['SMS economics require close tracking','not an email-first tool'],'SMSBump is a recognizable SMS option for cart recovery, campaigns, and subscriber collection on Shopify.',['sms','marketing','cart recovery']],
 ['tinyemail','tinyEmail','AI-assisted email marketing','budget-sensitive shops that want quick campaign drafting and basic Shopify sync','Free and paid plans by subscribers/features',['fast campaign creation','AI-assisted copy features','accessible pricing'],['lighter automation depth','not as battle-tested for complex ecommerce programs'],'tinyEmail can work for young stores that need campaigns live quickly before graduating to deeper lifecycle tooling.',['email','marketing']]
].map(([slug,name,category,bestFor,pricing,strengths,limits,shopifyFit,channels])=>({slug,name,category,bestFor,pricing,strengths,limits,shopifyFit,channels})) as App[];

export const SEGMENTS = [
 ['fashion','fashion stores','seasonality, size availability, drops, and fast-moving inventory'],['beauty','beauty brands','replenishment timing, bundles, subscriptions, shades, and routine education'],['supplements','supplement stores','compliance-safe claims, subscriptions, replenishment, and education'],['jewelry','jewelry stores','gift timing, high-consideration purchases, and trust-building'],['home-goods','home goods stores','larger catalogs, style preferences, and delayed purchase cycles'],['food-and-beverage','food and beverage brands','repeat purchase windows, subscriptions, and limited-time flavors'],['pet-products','pet product stores','pet lifecycle, reorder timing, and product education'],['digital-products','digital product shops','delivery, onboarding, cross-sells, and low-inventory constraints'],['print-on-demand','print-on-demand stores','trend cycles, personalization, and margin-sensitive promos'],['high-aov','high-AOV stores','longer consideration, trust, financing, and expert proof'],['subscription-boxes','subscription box brands','subscriber retention, skips, churn, and upcoming-box previews'],['b2b-wholesale','B2B wholesale Shopify stores','account approvals, bulk ordering, and rep follow-up']
].map(([slug,name,pain])=>({slug,name,pain}));
export const USE_CASES = [
 ['welcome-series','welcome series','turn new subscribers into first-time buyers'],['abandoned-cart','abandoned cart recovery','bring shoppers back before intent disappears'],['browse-abandonment','browse abandonment','follow product interest without discounting too early'],['post-purchase','post-purchase education','reduce buyer anxiety and set up the next purchase'],['winback','winback campaigns','reactivate customers before they lapse permanently'],['replenishment','replenishment reminders','time repeat purchases around actual product usage'],['product-launch','product launch campaigns','coordinate drops, waitlists, and VIP early access'],['vip-segments','VIP customer campaigns','treat best customers differently from coupon hunters'],['discount-strategy','discount strategy','use incentives without training every shopper to wait'],['segmentation','Shopify segmentation','target by behavior, products, order count, and lifecycle stage'],['email-design','email design','make product-led campaigns readable and mobile-friendly'],['deliverability','deliverability','protect inbox placement while sending more lifecycle email'],['reviews-and-ugc','reviews and UGC','pull social proof into retention campaigns'],['loyalty','loyalty campaigns','convert repeat buyers into habitual customers'],['analytics','revenue analytics','measure incremental revenue, not only attributed clicks'],['black-friday','Black Friday campaigns','prepare high-volume campaigns without burning the list'],['holiday-gifting','holiday gifting','match gift timing, deadlines, and bundles'],['back-in-stock','back-in-stock alerts','capture demand for unavailable products']
].map(([slug,name,job])=>({slug,name,job}));
export function siteFromHost(host?: string | null): SiteProfile { const clean=(host||'').toLowerCase().replace(/^www\./,'').split(':')[0]; return SITES[(DOMAINS.includes(clean as SiteKey)?clean:'shopifyemailmarketingapps.com') as SiteKey]; }
export function appBySlug(slug:string){ return APPS.find(a=>a.slug===slug); }
export function appPairs(){ const pairs:[App,App][]=[]; for(let i=0;i<APPS.length;i++) for(let j=i+1;j<Math.min(APPS.length,i+7);j++) pairs.push([APPS[i],APPS[j]]); return pairs.slice(0,70); }
export function allPaths(){ const paths=['','apps','compare','guides','use-cases','for']; APPS.forEach(a=>paths.push(`apps/${a.slug}`)); appPairs().forEach(([a,b])=>paths.push(`compare/${a.slug}-vs-${b.slug}`)); SEGMENTS.forEach(s=>paths.push(`for/${s.slug}`)); USE_CASES.forEach(u=>paths.push(`use-cases/${u.slug}`)); APPS.slice(1).forEach(a=>paths.push(`alternatives/${a.slug}-alternative`)); return paths; }
export function pageTitle(site:SiteProfile,path:string){ if(!path) return `Best ${site.primaryKeyword} in 2026`; const p=path.split('/'); if(p[0]==='apps'){ if(!p[1]) return `Best ${site.keywordPlural}: 20 Shopify Apps Compared`; const a=appBySlug(p[1]); return `${a?.name || 'Shopify App'} Review for ${site.primaryKeyword}`;} if(p[0]==='compare'){ if(!p[1]) return `${site.primaryKeyword} Comparison Hub`; const [a,b]=p[1].split('-vs-').map(appBySlug); return `${a?.name} vs ${b?.name}: Best for Shopify?`;} if(p[0]==='for'){ if(!p[1]) return `${site.primaryKeyword} by Shopify Store Type`; const s=SEGMENTS.find(x=>x.slug===p[1]); return `Best ${site.primaryKeyword} for ${s?.name || 'Shopify Stores'}`;} if(p[0]==='use-cases'){ if(!p[1]) return `${site.primaryKeyword} Use Cases`; const u=USE_CASES.find(x=>x.slug===p[1]); return `Best ${site.primaryKeyword} for ${u?.name || 'Shopify Growth'}`;} if(p[0]==='alternatives'){ const a=appBySlug((p[1]||'').replace('-alternative','')); return `Best ${a?.name || 'App'} Alternatives for Shopify`;} if(p[0]==='guides') return `${site.primaryKeyword} Guides and Playbooks`; return `Best ${site.primaryKeyword}`; }
export function description(site:SiteProfile,path:string){ return `${pageTitle(site,path)}. A practical Shopify-focused guide covering fit, pricing, automation depth, segmentation, compliance, analytics, and when to choose each app.`; }
